rapigrow:
  db:
    username: root
    password: Punitu37y5a#
    host: localhost
    port: 3306
    name: RapiGrow
    url: jdbc:mysql://
server:
  servlet:
    context-path: /api/v1
logging:
  level:
    web: DEBUG

spring:
  cloud:
    gcp:
      logging:
        enabled: true